// Maps ticker symbols to their common company names for text highlighting

export const TICKER_TO_COMPANY: Record<string, string[]> = {
  AAPL: ["Apple"],
  MSFT: ["Microsoft"],
  GOOGL: ["Google", "Alphabet"],
  GOOG: ["Google", "Alphabet"],
  AMZN: ["Amazon"],
  NVDA: ["Nvidia"],
  TSLA: ["Tesla"],
  META: ["Meta", "Facebook"],
  NFLX: ["Netflix"],
  AMD: ["AMD"],
  INTC: ["Intel"],
  ORCL: ["Oracle"],
  CRM: ["Salesforce"],
  ADBE: ["Adobe"],
  PYPL: ["PayPal"],
  DIS: ["Disney"],
  BA: ["Boeing"],
  GE: ["General Electric"],
  JPM: ["JPMorgan", "JP Morgan"],
  BAC: ["Bank of America"],
  WMT: ["Walmart"],
  V: ["Visa"],
  MA: ["Mastercard"],
  PFE: ["Pfizer"],
  JNJ: ["Johnson & Johnson"],
  KO: ["Coca-Cola", "Coca Cola"],
  PEP: ["PepsiCo", "Pepsi"],
  NKE: ["Nike"],
  MCD: ["McDonald's", "McDonalds"],
  SBUX: ["Starbucks"],
  T: ["AT&T"],
  VZ: ["Verizon"],
  CMCSA: ["Comcast"],
  CMG: ["Chipotle"],
  CSCO: ["Cisco"],
  C: ["Citigroup"],
  COST: ["Costco"],
  LULU: ["Lululemon"],
};
