// Maps ticker symbols to their common company names for text highlighting
// Top 1000 stocks by market cap (actively traded)

export const TICKER_TO_COMPANY: Record<string, string[]> = {
  // Mega Cap Tech
  AAPL: ["Apple"],
  MSFT: ["Microsoft"],
  GOOGL: ["Google", "Alphabet"],
  GOOG: ["Google", "Alphabet"],
  AMZN: ["Amazon"],
  NVDA: ["Nvidia"],
  META: ["Meta", "Facebook"],
  TSLA: ["Tesla"],
  AVGO: ["Broadcom"],

  // Large Cap Tech
  ORCL: ["Oracle"],
  CRM: ["Salesforce"],
  ADBE: ["Adobe"],
  NFLX: ["Netflix"],
  AMD: ["AMD"],
  INTC: ["Intel"],
  CSCO: ["Cisco"],
  QCOM: ["Qualcomm"],
  TXN: ["Texas Instruments"],
  NOW: ["ServiceNow"],
  INTU: ["Intuit"],
  PANW: ["Palo Alto Networks"],
  AMAT: ["Applied Materials"],
  MU: ["Micron", "Micron Technology"],
  ADI: ["Analog Devices"],
  LRCX: ["Lam Research"],
  KLAC: ["KLA"],
  SNPS: ["Synopsys"],
  CDNS: ["Cadence"],
  MRVL: ["Marvell"],
  FTNT: ["Fortinet"],
  CRWD: ["CrowdStrike"],
  ADSK: ["Autodesk"],
  WDAY: ["Workday"],
  TEAM: ["Atlassian"],
  DDOG: ["Datadog"],
  ZS: ["Zscaler"],
  SNOW: ["Snowflake"],
  NET: ["Cloudflare"],
  PLTR: ["Palantir"],
  UBER: ["Uber"],
  ABNB: ["Airbnb"],
  SQ: ["Block", "Square"],
  SHOP: ["Shopify"],
  SPOT: ["Spotify"],
  RBLX: ["Roblox"],
  U: ["Unity"],

  // Communication & Media
  TMUS: ["T-Mobile"],
  VZ: ["Verizon"],
  T: ["AT&T"],
  CMCSA: ["Comcast"],
  CHTR: ["Charter"],
  DIS: ["Disney"],
  NWSA: ["News Corp"],
  FOXA: ["Fox"],
  PARA: ["Paramount"],
  WBD: ["Warner Bros Discovery"],
  MTCH: ["Match Group"],
  EA: ["Electronic Arts"],
  TTWO: ["Take-Two"],

  // Consumer Discretionary
  HD: ["Home Depot"],
  MCD: ["McDonald's", "McDonalds"],
  NKE: ["Nike"],
  SBUX: ["Starbucks"],
  LOW: ["Lowe's", "Lowes"],
  TJX: ["TJX", "TJ Maxx"],
  BKNG: ["Booking"],
  CMG: ["Chipotle"],
  MAR: ["Marriott"],
  GM: ["General Motors"],
  F: ["Ford"],
  TM: ["Toyota"],
  HMC: ["Honda"],
  RIVN: ["Rivian"],
  LCID: ["Lucid"],
  NIO: ["Nio"],
  LI: ["Li Auto"],
  XPEV: ["XPeng"],
  YUM: ["Yum Brands"],
  QSR: ["Restaurant Brands"],
  DPZ: ["Domino's", "Dominos"],
  DRI: ["Darden"],
  WEN: ["Wendy's", "Wendys"],
  JACK: ["Jack in the Box"],
  SHAK: ["Shake Shack"],
  WING: ["Wingstop"],
  TXRH: ["Texas Roadhouse"],
  LULU: ["Lululemon"],
  GPS: ["Gap"],
  ANF: ["Abercrombie"],
  URBN: ["Urban Outfitters"],
  AEO: ["American Eagle"],
  BBY: ["Best Buy"],
  TGT: ["Target"],
  WMT: ["Walmart"],
  COST: ["Costco"],
  DG: ["Dollar General"],
  DLTR: ["Dollar Tree"],
  KSS: ["Kohl's", "Kohls"],
  M: ["Macy's", "Macys"],
  JWN: ["Nordstrom"],
  ROST: ["Ross"],
  BURL: ["Burlington"],
  FL: ["Foot Locker"],
  CROX: ["Crocs"],
  DECK: ["Deckers"],
  SKX: ["Skechers"],
  TPR: ["Tapestry"],
  RL: ["Ralph Lauren"],
  PVH: ["PVH"],
  VFC: ["VF Corp"],
  UAA: ["Under Armour"],
  ETSY: ["Etsy"],
  W: ["Wayfair"],
  CHWY: ["Chewy"],
  CVNA: ["Carvana"],
  RH: ["RH", "Restoration Hardware"],
  WSM: ["Williams-Sonoma"],

  // Consumer Staples
  PG: ["Procter & Gamble"],
  KO: ["Coca-Cola", "Coca Cola"],
  PEP: ["PepsiCo", "Pepsi"],
  PM: ["Philip Morris"],
  MO: ["Altria"],
  MDLZ: ["Mondelez"],
  CL: ["Colgate"],
  KMB: ["Kimberly-Clark"],
  GIS: ["General Mills"],
  K: ["Kellogg"],
  KHC: ["Kraft Heinz"],
  HSY: ["Hershey"],
  STZ: ["Constellation Brands"],
  TAP: ["Molson Coors"],
  BUD: ["Anheuser-Busch"],
  KDP: ["Keurig Dr Pepper"],
  MNST: ["Monster"],
  CELH: ["Celsius"],
  CLX: ["Clorox"],
  CHD: ["Church & Dwight"],
  CAG: ["Conagra"],
  CPB: ["Campbell"],
  HRL: ["Hormel"],
  TSN: ["Tyson"],
  SJM: ["Smucker"],
  MKC: ["McCormick"],

  // Energy
  XOM: ["Exxon", "ExxonMobil"],
  CVX: ["Chevron"],
  COP: ["ConocoPhillips"],
  SLB: ["Schlumberger"],
  EOG: ["EOG Resources"],
  PXD: ["Pioneer"],
  MPC: ["Marathon Petroleum"],
  PSX: ["Phillips 66"],
  VLO: ["Valero"],
  OXY: ["Occidental"],
  HAL: ["Halliburton"],
  DVN: ["Devon"],
  FANG: ["Diamondback"],
  HES: ["Hess"],
  KMI: ["Kinder Morgan"],
  WMB: ["Williams"],
  OKE: ["Oneok"],
  LNG: ["Cheniere"],
  TRGP: ["Targa"],

  // Financials
  BRK_B: ["Berkshire Hathaway"],
  JPM: ["JPMorgan", "JP Morgan"],
  BAC: ["Bank of America"],
  WFC: ["Wells Fargo"],
  GS: ["Goldman Sachs"],
  MS: ["Morgan Stanley"],
  C: ["Citigroup"],
  BLK: ["BlackRock"],
  SCHW: ["Charles Schwab"],
  USB: ["US Bancorp"],
  PNC: ["PNC"],
  TFC: ["Truist"],
  COF: ["Capital One"],
  AXP: ["American Express"],
  V: ["Visa"],
  MA: ["Mastercard"],
  PYPL: ["PayPal"],
  FIS: ["Fidelity National"],
  FISV: ["Fiserv"],
  ADP: ["ADP"],
  SPGI: ["S&P Global"],
  MCO: ["Moody's", "Moodys"],
  ICE: ["Intercontinental Exchange"],
  CME: ["CME Group"],
  AON: ["Aon"],
  MMC: ["Marsh McLennan"],
  AJG: ["Gallagher"],
  BRO: ["Brown & Brown"],
  PGR: ["Progressive"],
  ALL: ["Allstate"],
  TRV: ["Travelers"],
  MET: ["MetLife"],
  PRU: ["Prudential"],
  AFL: ["Aflac"],
  AIG: ["AIG"],
  CB: ["Chubb"],
  HIG: ["Hartford"],
  WRB: ["Berkley"],
  BK: ["Bank of New York"],
  STT: ["State Street"],
  NTRS: ["Northern Trust"],
  CFG: ["Citizens"],
  KEY: ["KeyCorp"],
  RF: ["Regions"],
  HBAN: ["Huntington"],
  FITB: ["Fifth Third"],
  MTB: ["M&T Bank"],

  // Healthcare
  UNH: ["UnitedHealth"],
  JNJ: ["Johnson & Johnson"],
  LLY: ["Eli Lilly"],
  ABBV: ["AbbVie"],
  MRK: ["Merck"],
  TMO: ["Thermo Fisher"],
  ABT: ["Abbott"],
  DHR: ["Danaher"],
  PFE: ["Pfizer"],
  AMGN: ["Amgen"],
  BMY: ["Bristol Myers"],
  GILD: ["Gilead"],
  VRTX: ["Vertex"],
  REGN: ["Regeneron"],
  CI: ["Cigna"],
  CVS: ["CVS"],
  HUM: ["Humana"],
  ELV: ["Elevance"],
  CNC: ["Centene"],
  MOH: ["Molina"],
  MCK: ["McKesson"],
  CAH: ["Cardinal Health"],
  COR: ["Cencora"],
  VTRS: ["Viatris"],
  ZTS: ["Zoetis"],
  IDXX: ["Idexx"],
  DGX: ["Quest Diagnostics"],
  LH: ["Labcorp"],
  SYK: ["Stryker"],
  BSX: ["Boston Scientific"],
  MDT: ["Medtronic"],
  EW: ["Edwards Lifesciences"],
  ISRG: ["Intuitive Surgical"],
  RMD: ["ResMed"],
  DXCM: ["Dexcom"],
  HOLX: ["Hologic"],
  BDX: ["Becton Dickinson"],
  BAX: ["Baxter"],
  ALGN: ["Align"],
  PODD: ["Insulet"],
  TECH: ["Bio-Techne"],
  WAT: ["Waters"],
  A: ["Agilent"],
  IQV: ["IQVIA"],
  CRL: ["Charles River"],
  BIIB: ["Biogen"],
  MRNA: ["Moderna"],
  ALNY: ["Alnylam"],
  EXAS: ["Exact Sciences"],
  INCY: ["Incyte"],
  NBIX: ["Neurocrine"],

  // Industrials
  BA: ["Boeing"],
  GE: ["General Electric"],
  CAT: ["Caterpillar"],
  RTX: ["Raytheon"],
  HON: ["Honeywell"],
  UNP: ["Union Pacific"],
  UPS: ["UPS"],
  DE: ["Deere"],
  LMT: ["Lockheed Martin"],
  NOC: ["Northrop Grumman"],
  GD: ["General Dynamics"],
  TDG: ["TransDigm"],
  EMR: ["Emerson"],
  ETN: ["Eaton"],
  ITW: ["Illinois Tool"],
  PH: ["Parker Hannifin"],
  CMI: ["Cummins"],
  PCAR: ["Paccar"],
  FDX: ["FedEx"],
  NSC: ["Norfolk Southern"],
  CSX: ["CSX"],
  WM: ["Waste Management"],
  RSG: ["Republic Services"],
  VRSK: ["Verisk"],
  ROK: ["Rockwell"],
  AME: ["Ametek"],
  FAST: ["Fastenal"],
  DOV: ["Dover"],
  IR: ["Ingersoll Rand"],
  OTIS: ["Otis"],
  CARR: ["Carrier"],
  JCI: ["Johnson Controls"],
  SWK: ["Stanley Black & Decker"],
  MAS: ["Masco"],
  BLDR: ["Builders FirstSource"],
  LHX: ["L3Harris"],
  HWM: ["Howmet"],
  TXT: ["Textron"],
  HII: ["Huntington Ingalls"],

  // Materials
  LIN: ["Linde"],
  APD: ["Air Products"],
  SHW: ["Sherwin-Williams"],
  ECL: ["Ecolab"],
  FCX: ["Freeport"],
  NEM: ["Newmont"],
  DD: ["DuPont"],
  DOW: ["Dow"],
  PPG: ["PPG"],
  NUE: ["Nucor"],
  STLD: ["Steel Dynamics"],
  VMC: ["Vulcan"],
  MLM: ["Martin Marietta"],
  ALB: ["Albemarle"],
  CE: ["Celanese"],
  EMN: ["Eastman"],
  CF: ["CF Industries"],
  MOS: ["Mosaic"],
  FMC: ["FMC"],
  IFF: ["IFF"],

  // Real Estate
  AMT: ["American Tower"],
  PLD: ["Prologis"],
  CCI: ["Crown Castle"],
  EQIX: ["Equinix"],
  PSA: ["Public Storage"],
  DLR: ["Digital Realty"],
  WELL: ["Welltower"],
  O: ["Realty Income"],
  SPG: ["Simon Property"],
  VICI: ["VICI"],
  SBAC: ["SBA Communications"],
  AVB: ["AvalonBay"],
  EQR: ["Equity Residential"],
  VTR: ["Ventas"],
  ARE: ["Alexandria Real Estate"],
  INVH: ["Invitation Homes"],
  MAA: ["Mid-America"],
  ESS: ["Essex"],
  UDR: ["UDR"],
  CPT: ["Camden"],

  // Utilities
  NEE: ["NextEra"],
  DUK: ["Duke"],
  SO: ["Southern"],
  D: ["Dominion"],
  AEP: ["American Electric"],
  EXC: ["Exelon"],
  SRE: ["Sempra"],
  XEL: ["Xcel"],
  WEC: ["WEC Energy"],
  ED: ["Con Edison"],
  PEG: ["Public Service"],
  ES: ["Eversource"],
  FE: ["FirstEnergy"],
  EIX: ["Edison International"],
  ETR: ["Entergy"],
  DTE: ["DTE Energy"],
  PPL: ["PPL"],
  CMS: ["CMS Energy"],
  AEE: ["Ameren"],

  // International
  BABA: ["Alibaba"],
  TSM: ["TSMC", "Taiwan Semi"],
  NVO: ["Novo Nordisk"],
  ASML: ["ASML"],
  SONY: ["Sony"],
  SAP: ["SAP"],
  NESN: ["Nestle"],
  UL: ["Unilever"],
  SNY: ["Sanofi"],
  BHP: ["BHP"],
  RIO: ["Rio Tinto"],
  BP: ["BP"],
  HSBC: ["HSBC"],
  TD: ["TD Bank"],
  RY: ["Royal Bank"],
  BNS: ["Scotiabank"],
  BIDU: ["Baidu"],
  NVS: ["Novartis"],

  // ETFs & Indices
  SPY: ["S&P 500"],
  QQQ: ["Nasdaq"],
  IWM: ["Russell 2000"],
  DIA: ["Dow Jones"],
  VTI: ["Total Market"],
  VOO: ["S&P 500"],

  // Software & Cloud
  OKTA: ["Okta"],
  HUBS: ["HubSpot"],
  VEEV: ["Veeva"],
  ZM: ["Zoom"],
  DOCU: ["DocuSign"],
  TWLO: ["Twilio"],
  SPLK: ["Splunk"],
  MDB: ["MongoDB"],
  ESTC: ["Elastic"],
  CFLT: ["Confluent"],
  PATH: ["UiPath"],
  BILL: ["Bill.com"],
  S: ["SentinelOne"],
  GTLB: ["GitLab"],
  FROG: ["JFrog"],
  PCTY: ["Paylocity"],
  PAYC: ["Paycom"],
  ZI: ["ZoomInfo"],

  // Semiconductors (additional)
  NXPI: ["NXP"],
  MCHP: ["Microchip"],
  ON: ["ON Semi"],
  MPWR: ["Monolithic Power"],
  SWKS: ["Skyworks"],
  QRVO: ["Qorvo"],
  WOLF: ["Wolfspeed"],

  // Biotech & Pharma (additional)
  SGEN: ["Seagen"],
  BGNE: ["BeiGene"],
  IONS: ["Ionis"],
  UTHR: ["United Therapeutics"],
  JAZZ: ["Jazz Pharma"],
  ACAD: ["Acadia"],
  SRPT: ["Sarepta"],
  RARE: ["Ultragenyx"],
  BMRN: ["BioMarin"],
  BLUE: ["Bluebird Bio"],
  CRSP: ["CRISPR"],
  EDIT: ["Editas"],
  NTLA: ["Intellia"],
  BEAM: ["Beam Therapeutics"],
  ARWR: ["Arrowhead"],
  RGNX: ["Regenxbio"],

  // Aerospace & Defense (additional)
  LDOS: ["Leidos"],

  // Retail (additional)
  FIVE: ["Five Below"],
  OLLI: ["Ollie's"],
  BIG: ["Big Lots"],
  BBWI: ["Bath & Body Works"],
  DKS: ["Dick's Sporting Goods"],
  ULTA: ["Ulta"],
  GES: ["Guess"],
  VSCO: ["Victoria's Secret"],

  // Restaurants (additional)
  DNKN: ["Dunkin"],
  BROS: ["Dutch Bros"],
  CAVA: ["Cava"],
  CAKE: ["Cheesecake Factory"],
  DNUT: ["Krispy Kreme"],
  PZZA: ["Papa John's"],

  // E-Commerce & Digital
  MELI: ["MercadoLibre"],
  SE: ["Sea Limited"],
  CPNG: ["Coupang"],
  DASH: ["DoorDash"],
  LYFT: ["Lyft"],
  GRAB: ["Grab"],

  // Media (additional)
  LYV: ["Live Nation"],
  MSG: ["Madison Square Garden"],
  MSGS: ["MSG Sports"],

  // Crypto & Fintech
  COIN: ["Coinbase"],
  HOOD: ["Robinhood"],
  SOFI: ["SoFi"],
  AFRM: ["Affirm"],
  UPST: ["Upstart"],
  LC: ["LendingClub"],
  NU: ["Nu Holdings"],

  // Cannabis
  TLRY: ["Tilray"],
  CGC: ["Canopy Growth"],
  SNDL: ["Sundial"],
  ACB: ["Aurora Cannabis"],

  // Space & Defense Tech
  SPCE: ["Virgin Galactic"],
  RKLB: ["Rocket Lab"],
  ASTS: ["AST SpaceMobile"],

  // Renewable Energy
  ENPH: ["Enphase"],
  SEDG: ["SolarEdge"],
  RUN: ["Sunrun"],
  NOVA: ["Sunnova"],
  FSLR: ["First Solar"],

  // Medical Devices (additional)
  ZBH: ["Zimmer Biomet"],
  XRAY: ["Dentsply Sirona"],
  TNDM: ["Tandem"],
  ABMD: ["Abiomed"],

  // Commercial Services
  CTAS: ["Cintas"],
  ROP: ["Roper"],
  FTV: ["Fortive"],
  IEX: ["IDEX"],
  PNR: ["Pentair"],
  WST: ["West Pharmaceutical"],
  POOL: ["Pool Corp"],

  // Transportation
  UAL: ["United Airlines"],
  DAL: ["Delta"],
  AAL: ["American Airlines"],
  LUV: ["Southwest"],
  ALK: ["Alaska Air"],
  JBLU: ["JetBlue"],
  SAVE: ["Spirit Airlines"],

  // Logistics (additional)
  CHRW: ["Robinson Worldwide"],
  EXPD: ["Expeditors"],
  XPO: ["XPO Logistics"],
  JBHT: ["Hunt Transport"],

  // Tobacco (additional)
  BTI: ["British American Tobacco"],

  // Alcohol (additional)
  SAM: ["Boston Beer"],
  BREW: ["Craft Brew Alliance"],

  // Beauty (additional)
  EL: ["Estee Lauder"],

  // Gaming (additional)
  ATVI: ["Activision"],
  ZNGA: ["Zynga"],

  // Payments (additional)
  GPN: ["Global Payments"],

  // Analytics (additional)
  MSCI: ["MSCI"],
  IHS: ["IHS Markit"],

  // Construction (additional)
  FND: ["Floor & Decor"],
};
