// Maps ticker symbols to their common company names for text highlighting
// Top 1000 stocks by market cap (actively traded)

export const TICKER_TO_COMPANY: Record<string, string[]> = {
  // Mega Cap Tech
  AAPL: ["Apple"],
  MSFT: ["Microsoft"],
  GOOGL: ["Google", "Alphabet"],
  GOOG: ["Google", "Alphabet"],
  AMZN: ["Amazon"],
  NVDA: ["Nvidia"],
  META: ["Meta", "Facebook"],
  TSLA: ["Tesla"],
  AVGO: ["Broadcom"],

  // Large Cap Tech
  ORCL: ["Oracle"],
  CRM: ["Salesforce"],
  ADBE: ["Adobe"],
  NFLX: ["Netflix"],
  AMD: ["Advanced Micro Devices"],
  INTC: ["Intel"],
  CSCO: ["Cisco"],
  QCOM: ["Qualcomm"],
  TXN: ["Texas Instruments"],
  NOW: ["ServiceNow"],
  INTU: ["Intuit"],
  PANW: ["Palo Alto Networks"],
  AMAT: ["Applied Materials"],
  MU: ["Micron", "Micron Technology"],
  ADI: ["Analog Devices"],
  LRCX: ["Lam Research"],
  KLAC: ["KLA"],
  SNPS: ["Synopsys"],
  CDNS: ["Cadence"],
  MRVL: ["Marvell"],
  FTNT: ["Fortinet"],
  CRWD: ["CrowdStrike"],
  ADSK: ["Autodesk"],
  WDAY: ["Workday"],
  TEAM: ["Atlassian"],
  DDOG: ["Datadog"],
  ZS: ["Zscaler"],
  SNOW: ["Snowflake"],
  NET: ["Cloudflare"],
  PLTR: ["Palantir"],
  UBER: ["Uber"],
  ABNB: ["Airbnb"],
  SQ: ["Block", "Square"],
  SHOP: ["Shopify"],
  SPOT: ["Spotify"],
  RBLX: ["Roblox"],
  U: ["Unity"],

  // Communication & Media
  TMUS: ["T-Mobile"],
  VZ: ["Verizon"],
  T: ["AT&T"],
  CMCSA: ["Comcast"],
  CHTR: ["Charter"],
  DIS: ["Disney"],
  NWSA: ["News Corp"],
  FOXA: ["Fox"],
  PARA: ["Paramount"],
  WBD: ["Warner Bros Discovery"],
  MTCH: ["Match Group"],
  EA: ["Electronic Arts"],
  TTWO: ["Take-Two"],

  // Consumer Discretionary
  HD: ["Home Depot"],
  MCD: ["McDonald's", "McDonalds"],
  NKE: ["Nike"],
  SBUX: ["Starbucks"],
  LOW: ["Lowe's", "Lowes"],
  TJX: ["TJX", "TJ Maxx"],
  BKNG: ["Booking"],
  CMG: ["Chipotle"],
  MAR: ["Marriott"],
  GM: ["General Motors"],
  F: ["Ford"],
  TM: ["Toyota"],
  HMC: ["Honda"],
  RIVN: ["Rivian"],
  LCID: ["Lucid"],
  NIO: ["Nio"],
  LI: ["Li Auto"],
  XPEV: ["XPeng"],
  YUM: ["Yum Brands"],
  QSR: ["Restaurant Brands"],
  DPZ: ["Domino's", "Dominos"],
  DRI: ["Darden"],
  WEN: ["Wendy's", "Wendys"],
  JACK: ["Jack in the Box"],
  SHAK: ["Shake Shack"],
  WING: ["Wingstop"],
  TXRH: ["Texas Roadhouse"],
  LULU: ["Lululemon"],
  GPS: ["Gap"],
  ANF: ["Abercrombie"],
  URBN: ["Urban Outfitters"],
  AEO: ["American Eagle"],
  BBY: ["Best Buy"],
  TGT: ["Target"],
  WMT: ["Walmart"],
  COST: ["Costco"],
  DG: ["Dollar General"],
  DLTR: ["Dollar Tree"],
  KSS: ["Kohl's", "Kohls"],
  M: ["Macy's", "Macys"],
  JWN: ["Nordstrom"],
  ROST: ["Ross"],
  BURL: ["Burlington"],
  FL: ["Foot Locker"],
  CROX: ["Crocs"],
  DECK: ["Deckers"],
  SKX: ["Skechers"],
  TPR: ["Tapestry"],
  RL: ["Ralph Lauren"],
  PVH: ["PVH"],
  VFC: ["VF Corp"],
  UAA: ["Under Armour"],
  ETSY: ["Etsy"],
  W: ["Wayfair"],
  CHWY: ["Chewy"],
  CVNA: ["Carvana"],
  RH: ["RH", "Restoration Hardware"],
  WSM: ["Williams-Sonoma"],

  // Consumer Staples
  PG: ["Procter & Gamble"],
  KO: ["Coca-Cola", "Coca Cola"],
  PEP: ["PepsiCo", "Pepsi"],
  PM: ["Philip Morris"],
  MO: ["Altria"],
  MDLZ: ["Mondelez"],
  CL: ["Colgate"],
  KMB: ["Kimberly-Clark"],
  GIS: ["General Mills"],
  K: ["Kellogg"],
  KHC: ["Kraft Heinz"],
  HSY: ["Hershey"],
  STZ: ["Constellation Brands"],
  TAP: ["Molson Coors"],
  BUD: ["Anheuser-Busch"],
  KDP: ["Keurig Dr Pepper"],
  MNST: ["Monster"],
  CELH: ["Celsius"],
  CLX: ["Clorox"],
  CHD: ["Church & Dwight"],
  CAG: ["Conagra"],
  CPB: ["Campbell"],
  HRL: ["Hormel"],
  TSN: ["Tyson"],
  SJM: ["Smucker"],
  MKC: ["McCormick"],

  // Energy
  XOM: ["Exxon", "ExxonMobil"],
  CVX: ["Chevron"],
  COP: ["ConocoPhillips"],
  SLB: ["Schlumberger"],
  EOG: ["EOG Resources"],
  PXD: ["Pioneer"],
  MPC: ["Marathon Petroleum"],
  PSX: ["Phillips 66"],
  VLO: ["Valero"],
  OXY: ["Occidental"],
  HAL: ["Halliburton"],
  DVN: ["Devon"],
  FANG: ["Diamondback"],
  HES: ["Hess"],
  KMI: ["Kinder Morgan"],
  WMB: ["Williams"],
  OKE: ["Oneok"],
  LNG: ["Cheniere"],
  TRGP: ["Targa"],

  // Financials
  BRK_B: ["Berkshire Hathaway"],
  JPM: ["JPMorgan", "JP Morgan"],
  BAC: ["Bank of America"],
  WFC: ["Wells Fargo"],
  GS: ["Goldman Sachs"],
  MS: ["Morgan Stanley"],
  C: ["Citigroup"],
  BLK: ["BlackRock"],
  SCHW: ["Charles Schwab"],
  USB: ["US Bancorp"],
  PNC: ["PNC"],
  TFC: ["Truist"],
  COF: ["Capital One"],
  AXP: ["American Express"],
  V: ["Visa"],
  MA: ["Mastercard"],
  PYPL: ["PayPal"],
  FIS: ["Fidelity National"],
  FISV: ["Fiserv"],
  ADP: ["ADP"],
  SPGI: ["S&P Global"],
  MCO: ["Moody's", "Moodys"],
  ICE: ["Intercontinental Exchange"],
  CME: ["CME Group"],
  AON: ["Aon"],
  MMC: ["Marsh McLennan"],
  AJG: ["Gallagher"],
  BRO: ["Brown & Brown"],
  PGR: ["Progressive"],
  ALL: ["Allstate"],
  TRV: ["Travelers"],
  MET: ["MetLife"],
  PRU: ["Prudential"],
  AFL: ["Aflac"],
  AIG: ["AIG"],
  CB: ["Chubb"],
  HIG: ["Hartford"],
  WRB: ["Berkley"],
  BK: ["Bank of New York"],
  STT: ["State Street"],
  NTRS: ["Northern Trust"],
  CFG: ["Citizens"],
  KEY: ["KeyCorp"],
  RF: ["Regions"],
  HBAN: ["Huntington"],
  FITB: ["Fifth Third"],
  MTB: ["M&T Bank"],

  // Healthcare
  UNH: ["UnitedHealth"],
  JNJ: ["Johnson & Johnson"],
  LLY: ["Eli Lilly"],
  ABBV: ["AbbVie"],
  MRK: ["Merck"],
  TMO: ["Thermo Fisher"],
  ABT: ["Abbott"],
  DHR: ["Danaher"],
  PFE: ["Pfizer"],
  AMGN: ["Amgen"],
  BMY: ["Bristol Myers"],
  GILD: ["Gilead"],
  VRTX: ["Vertex"],
  REGN: ["Regeneron"],
  CI: ["Cigna"],
  CVS: ["CVS"],
  HUM: ["Humana"],
  ELV: ["Elevance"],
  CNC: ["Centene"],
  MOH: ["Molina"],
  MCK: ["McKesson"],
  CAH: ["Cardinal Health"],
  COR: ["Cencora"],
  VTRS: ["Viatris"],
  ZTS: ["Zoetis"],
  IDXX: ["Idexx"],
  DGX: ["Quest Diagnostics"],
  LH: ["Labcorp"],
  SYK: ["Stryker"],
  BSX: ["Boston Scientific"],
  MDT: ["Medtronic"],
  EW: ["Edwards Lifesciences"],
  ISRG: ["Intuitive Surgical"],
  RMD: ["ResMed"],
  DXCM: ["Dexcom"],
  HOLX: ["Hologic"],
  BDX: ["Becton Dickinson"],
  BAX: ["Baxter"],
  ALGN: ["Align"],
  PODD: ["Insulet"],
  TECH: ["Bio-Techne"],
  WAT: ["Waters"],
  A: ["Agilent"],
  IQV: ["IQVIA"],
  CRL: ["Charles River"],
  BIIB: ["Biogen"],
  MRNA: ["Moderna"],
  ALNY: ["Alnylam"],
  EXAS: ["Exact Sciences"],
  INCY: ["Incyte"],
  NBIX: ["Neurocrine"],

  // Industrials
  BA: ["Boeing"],
  GE: ["General Electric"],
  CAT: ["Caterpillar"],
  RTX: ["Raytheon"],
  HON: ["Honeywell"],
  UNP: ["Union Pacific"],
  UPS: ["UPS"],
  DE: ["Deere"],
  LMT: ["Lockheed Martin"],
  NOC: ["Northrop Grumman"],
  GD: ["General Dynamics"],
  TDG: ["TransDigm"],
  EMR: ["Emerson"],
  ETN: ["Eaton"],
  ITW: ["Illinois Tool"],
  PH: ["Parker Hannifin"],
  CMI: ["Cummins"],
  PCAR: ["Paccar"],
  FDX: ["FedEx"],
  NSC: ["Norfolk Southern"],
  CSX: ["CSX"],
  WM: ["Waste Management"],
  RSG: ["Republic Services"],
  VRSK: ["Verisk"],
  ROK: ["Rockwell"],
  AME: ["Ametek"],
  FAST: ["Fastenal"],
  DOV: ["Dover"],
  IR: ["Ingersoll Rand"],
  OTIS: ["Otis"],
  CARR: ["Carrier"],
  JCI: ["Johnson Controls"],
  SWK: ["Stanley Black & Decker"],
  MAS: ["Masco"],
  BLDR: ["Builders FirstSource"],
  LHX: ["L3Harris"],
  HWM: ["Howmet"],
  TXT: ["Textron"],
  HII: ["Huntington Ingalls"],

  // Materials
  LIN: ["Linde"],
  APD: ["Air Products"],
  SHW: ["Sherwin-Williams"],
  ECL: ["Ecolab"],
  FCX: ["Freeport"],
  NEM: ["Newmont"],
  DD: ["DuPont"],
  DOW: ["Dow"],
  PPG: ["PPG"],
  NUE: ["Nucor"],
  STLD: ["Steel Dynamics"],
  VMC: ["Vulcan"],
  MLM: ["Martin Marietta"],
  ALB: ["Albemarle"],
  CE: ["Celanese"],
  EMN: ["Eastman"],
  CF: ["CF Industries"],
  MOS: ["Mosaic"],
  FMC: ["FMC"],
  IFF: ["IFF"],

  // Real Estate
  AMT: ["American Tower"],
  PLD: ["Prologis"],
  CCI: ["Crown Castle"],
  EQIX: ["Equinix"],
  PSA: ["Public Storage"],
  DLR: ["Digital Realty"],
  WELL: ["Welltower"],
  O: ["Realty Income"],
  SPG: ["Simon Property"],
  VICI: ["VICI"],
  SBAC: ["SBA Communications"],
  AVB: ["AvalonBay"],
  EQR: ["Equity Residential"],
  VTR: ["Ventas"],
  ARE: ["Alexandria Real Estate"],
  INVH: ["Invitation Homes"],
  MAA: ["Mid-America"],
  ESS: ["Essex"],
  UDR: ["UDR"],
  CPT: ["Camden"],

  // Utilities
  NEE: ["NextEra"],
  DUK: ["Duke"],
  SO: ["Southern"],
  D: ["Dominion"],
  AEP: ["American Electric"],
  EXC: ["Exelon"],
  SRE: ["Sempra"],
  XEL: ["Xcel"],
  WEC: ["WEC Energy"],
  ED: ["Con Edison"],
  PEG: ["Public Service"],
  ES: ["Eversource"],
  FE: ["FirstEnergy"],
  EIX: ["Edison International"],
  ETR: ["Entergy"],
  DTE: ["DTE Energy"],
  PPL: ["PPL"],
  CMS: ["CMS Energy"],
  AEE: ["Ameren"],

  // International
  BABA: ["Alibaba"],
  TSM: ["TSMC", "Taiwan Semi"],
  NVO: ["Novo Nordisk"],
  ASML: ["ASML"],
  SONY: ["Sony"],
  SAP: ["SAP"],
  NESN: ["Nestle"],
  UL: ["Unilever"],
  SNY: ["Sanofi"],
  BHP: ["BHP"],
  RIO: ["Rio Tinto"],
  BP: ["BP"],
  HSBC: ["HSBC"],
  TD: ["TD Bank"],
  RY: ["Royal Bank"],
  BNS: ["Scotiabank"],
  BIDU: ["Baidu"],
  NVS: ["Novartis"],

  // ETFs & Indices
  SPY: ["S&P 500"],
  QQQ: ["Nasdaq"],
  IWM: ["Russell 2000"],
  DIA: ["Dow Jones"],
  VTI: ["Total Market"],
  VOO: ["S&P 500"],

  // Software & Cloud
  OKTA: ["Okta"],
  HUBS: ["HubSpot"],
  VEEV: ["Veeva"],
  ZM: ["Zoom"],
  DOCU: ["DocuSign"],
  TWLO: ["Twilio"],
  SPLK: ["Splunk"],
  MDB: ["MongoDB"],
  ESTC: ["Elastic"],
  CFLT: ["Confluent"],
  PATH: ["UiPath"],
  BILL: ["Bill.com"],
  S: ["SentinelOne"],
  GTLB: ["GitLab"],
  FROG: ["JFrog"],
  PCTY: ["Paylocity"],
  PAYC: ["Paycom"],
  ZI: ["ZoomInfo"],

  // Semiconductors (additional)
  NXPI: ["NXP"],
  MCHP: ["Microchip"],
  ON: ["ON Semi"],
  MPWR: ["Monolithic Power"],
  SWKS: ["Skyworks"],
  QRVO: ["Qorvo"],
  WOLF: ["Wolfspeed"],

  // Biotech & Pharma (additional)
  SGEN: ["Seagen"],
  BGNE: ["BeiGene"],
  IONS: ["Ionis"],
  UTHR: ["United Therapeutics"],
  JAZZ: ["Jazz Pharma"],
  ACAD: ["Acadia"],
  SRPT: ["Sarepta"],
  RARE: ["Ultragenyx"],
  BMRN: ["BioMarin"],
  BLUE: ["Bluebird Bio"],
  CRSP: ["CRISPR"],
  EDIT: ["Editas"],
  NTLA: ["Intellia"],
  BEAM: ["Beam Therapeutics"],
  ARWR: ["Arrowhead"],
  RGNX: ["Regenxbio"],

  // Aerospace & Defense (additional)
  LDOS: ["Leidos"],

  // Retail (additional)
  FIVE: ["Five Below"],
  OLLI: ["Ollie's"],
  BIG: ["Big Lots"],
  BBWI: ["Bath & Body Works"],
  DKS: ["Dick's Sporting Goods"],
  ULTA: ["Ulta"],
  GES: ["Guess"],
  VSCO: ["Victoria's Secret"],

  // Restaurants (additional)
  DNKN: ["Dunkin"],
  BROS: ["Dutch Bros"],
  CAVA: ["Cava"],
  CAKE: ["Cheesecake Factory"],
  DNUT: ["Krispy Kreme"],
  PZZA: ["Papa John's"],

  // E-Commerce & Digital
  MELI: ["MercadoLibre"],
  SE: ["Sea Limited"],
  CPNG: ["Coupang"],
  DASH: ["DoorDash"],
  LYFT: ["Lyft"],
  GRAB: ["Grab"],

  // Media (additional)
  LYV: ["Live Nation"],
  MSG: ["Madison Square Garden"],
  MSGS: ["MSG Sports"],

  // Crypto & Fintech
  COIN: ["Coinbase"],
  HOOD: ["Robinhood"],
  SOFI: ["SoFi"],
  AFRM: ["Affirm"],
  UPST: ["Upstart"],
  LC: ["LendingClub"],
  NU: ["Nu Holdings"],

  // Cannabis
  TLRY: ["Tilray"],
  CGC: ["Canopy Growth"],
  SNDL: ["Sundial"],
  ACB: ["Aurora Cannabis"],

  // Space & Defense Tech
  SPCE: ["Virgin Galactic"],
  RKLB: ["Rocket Lab"],
  ASTS: ["AST SpaceMobile"],

  // Renewable Energy
  ENPH: ["Enphase"],
  SEDG: ["SolarEdge"],
  RUN: ["Sunrun"],
  NOVA: ["Sunnova"],
  FSLR: ["First Solar"],

  // Medical Devices (additional)
  ZBH: ["Zimmer Biomet"],
  XRAY: ["Dentsply Sirona"],
  TNDM: ["Tandem"],
  ABMD: ["Abiomed"],

  // Commercial Services
  CTAS: ["Cintas"],
  ROP: ["Roper"],
  FTV: ["Fortive"],
  IEX: ["IDEX"],
  PNR: ["Pentair"],
  WST: ["West Pharmaceutical"],
  POOL: ["Pool Corp"],

  // Transportation
  UAL: ["United Airlines"],
  DAL: ["Delta"],
  AAL: ["American Airlines"],
  LUV: ["Southwest"],
  ALK: ["Alaska Air"],
  JBLU: ["JetBlue"],
  SAVE: ["Spirit Airlines"],

  // Logistics (additional)
  CHRW: ["Robinson Worldwide"],
  EXPD: ["Expeditors"],
  XPO: ["XPO Logistics"],
  JBHT: ["Hunt Transport"],

  // Tobacco (additional)
  BTI: ["British American Tobacco"],

  // Alcohol (additional)
  SAM: ["Boston Beer"],
  BREW: ["Craft Brew Alliance"],

  // Beauty (additional)
  EL: ["Estee Lauder"],

  // Gaming (additional)
  ATVI: ["Activision"],
  ZNGA: ["Zynga"],

  // Payments (additional)
  GPN: ["Global Payments"],

  // Analytics (additional)
  MSCI: ["MSCI"],
  IHS: ["IHS Markit"],

  // Construction (additional)
  FND: ["Floor & Decor"],

  TQQQ: ["ProShares UltraPro QQQ"],
  SQQQ: ["ProShares UltraPro Short QQQ"],
  UPRO: ["ProShares UltraPro S&P 500"],
  SPXU: ["ProShares UltraPro Short S&P 500"],
  QLD: ["ProShares Ultra QQQ"],
  QID: ["ProShares UltraShort QQQ"],
  SSO: ["ProShares Ultra S&P 500"],
  SDS: ["ProShares UltraShort S&P 500"],
  TNA: ["Direxion Daily Small Cap Bull 3X"],
  TZA: ["Direxion Daily Small Cap Bear 3X"],
  SOXL: ["Direxion Daily Semiconductor Bull 3X"],
  SOXS: ["Direxion Daily Semiconductor Bear 3X"],
  TECL: ["Direxion Daily Technology Bull 3X"],
  TECS: ["Direxion Daily Technology Bear 3X"],
  LABU: ["Direxion Daily S&P Biotech Bull 3X"],
  LABD: ["Direxion Daily S&P Biotech Bear 3X"],
  FAS: ["Direxion Daily Financial Bull 3X"],
  FAZ: ["Direxion Daily Financial Bear 3X"],
  NUGT: ["Direxion Daily Gold Miners Bull 2X"],
  DUST: ["Direxion Daily Gold Miners Bear 2X"],

  // Dividend / Income ETFs
  JEPI: ["JPMorgan Equity Premium Income"],
  JEPQ: ["JPMorgan Nasdaq Equity Premium Income"],
  SCHD: ["Schwab U.S. Dividend Equity"],
  VYM: ["Vanguard High Dividend Yield"],
  HDV: ["iShares Core High Dividend"],
  DGRO: ["iShares Core Dividend Growth"],
  SPYD: ["SPDR Portfolio S&P 500 High Dividend"],
  DIVO: ["Amplify CWP Enhanced Dividend Income"],

  // Core / Style / Broad Market ETFs
  IVV: ["iShares Core S&P 500"],
  SPLG: ["SPDR Portfolio S&P 500"],
  SCHB: ["Schwab U.S. Broad Market"],
  ITOT: ["iShares Core S&P Total U.S. Stock Market"],
  VT: ["Vanguard Total World Stock"],
  VUG: ["Vanguard Growth"],
  VTV: ["Vanguard Value"],
  IWF: ["iShares Russell 1000 Growth"],
  IWD: ["iShares Russell 1000 Value"],

  // Sector ETFs
  XLK: ["Technology Select Sector SPDR"],
  XLF: ["Financial Select Sector SPDR"],
  XLE: ["Energy Select Sector SPDR"],
  XLV: ["Health Care Select Sector SPDR"],
  XLY: ["Consumer Discretionary Select Sector SPDR"],
  XLP: ["Consumer Staples Select Sector SPDR"],
  XLI: ["Industrial Select Sector SPDR"],
  XLB: ["Materials Select Sector SPDR"],
  XLU: ["Utilities Select Sector SPDR"],
  XLRE: ["Real Estate Select Sector SPDR"],
  XLC: ["Communication Services Select Sector SPDR"],

  // Thematic ETFs
  ARKK: ["ARK Innovation"],
  ARKQ: ["ARK Autonomous Technology & Robotics"],
  ARKW: ["ARK Next Generation Internet"],
  SMH: ["VanEck Semiconductor"],
  SOXX: ["iShares Semiconductor"],
  IGV: ["iShares Expanded Tech-Software Sector"],
  HACK: ["ETFMG Prime Cyber Security"],
  CIBR: ["First Trust NASDAQ Cybersecurity"],
  TAN: ["Invesco Solar"],
  ICLN: ["iShares Global Clean Energy"],
  XBI: ["SPDR S&P Biotech"],
  IBB: ["iShares Biotechnology"],
  KWEB: ["KraneShares CSI China Internet"],

  // Fixed Income / Rates / Credit ETFs
  TLT: ["iShares 20+ Year Treasury Bond"],
  IEF: ["iShares 7-10 Year Treasury Bond"],
  SHY: ["iShares 1-3 Year Treasury Bond"],
  BIL: ["SPDR Bloomberg 1-3 Month T-Bill"],
  SGOV: ["iShares 0-3 Month Treasury Bond"],
  LQD: ["iShares iBoxx Investment Grade Corporate Bond"],
  HYG: ["iShares iBoxx High Yield Corporate Bond"],
  AGG: ["iShares Core U.S. Aggregate Bond"],
  BND: ["Vanguard Total Bond Market"],
  TIP: ["iShares TIPS Bond"],

  // Commodities
  GLD: ["SPDR Gold Shares"],
  IAU: ["iShares Gold Trust"],
  SLV: ["iShares Silver Trust"],
  USO: ["United States Oil Fund"],
  UNG: ["United States Natural Gas Fund"],
  DBA: ["Invesco DB Agriculture Fund"],

  // Volatility
  VXX: ["iPath Series B S&P 500 VIX Short-Term Futures ETN"],
  UVXY: ["ProShares Ultra VIX Short-Term Futures"],
  SVXY: ["ProShares Short VIX Short-Term Futures"],

  // Crypto-related ETFs / Trusts
  BITO: ["ProShares Bitcoin Strategy ETF"],
  IBIT: ["iShares Bitcoin Trust"],
  FBTC: ["Fidelity Wise Origin Bitcoin Fund"],
  ARKB: ["ARK 21Shares Bitcoin ETF"],
  GBTC: ["Grayscale Bitcoin Trust"],
  ETHE: ["Grayscale Ethereum Trust"],

  // China / EM / FX (popular macro tickers)
  FXI: ["iShares China Large-Cap"],
  EEM: ["iShares MSCI Emerging Markets"],
  VWO: ["Vanguard FTSE Emerging Markets"],
  UUP: ["Invesco DB US Dollar Index Bullish Fund"],
  FXE: ["Invesco CurrencyShares Euro Trust"],
  FXY: ["Invesco CurrencyShares Japanese Yen Trust"],

  // Meme / Retail favorites
  GME: ["GameStop"],
  AMC: ["AMC Entertainment"],
  DKNG: ["DraftKings"],
  ROKU: ["Roku"],

  // Popular single-name “niche but common”
  MSTR: ["MicroStrategy"],
  PLUG: ["Plug Power"],
  MARA: ["Marathon Digital"],
  RIOT: ["Riot Platforms"],
  CLF: ["Cleveland-Cliffs"],
  X: ["United States Steel"],
  FCEL: ["FuelCell Energy"],
  BLNK: ["Blink Charging"],
  QS: ["QuantumScape"],
  IONQ: ["IonQ"],

  SNAP: ["Snap"],
  PINS: ["Pinterest"],
  BILI: ["Bilibili"],
  JD: ["JD.com"],
  PDD: ["PDD Holdings", "Pinduoduo"],
  TCEHY: ["Tencent"],
  SEHK_0700: ["Tencent"],
  PTON: ["Peloton"],
  FVRR: ["Fiverr"],
  UPWK: ["Upwork"],

  // Payments / Fintech (additional)
  PAYX: ["Paychex"],
  STNE: ["StoneCo"],
  PAGS: ["PagSeguro"],
  ADYEY: ["Adyen"],

  // Retail / Consumer (very common in news)
  KR: ["Kroger"],
  SFM: ["Sprouts Farmers Market"],
  ACI: ["Albertsons"],
  SIG: ["Signet Jewelers"],
  ASO: ["Academy Sports"],
  YETI: ["Yeti"],

  // Industrials / Cyclicals
  CCL: ["Carnival"],
  RCL: ["Royal Caribbean"],
  NCLH: ["Norwegian Cruise Line"],
  WAB: ["Wabtec"],
  AL: ["Air Lease"],
  AER: ["AerCap"],

  // Energy (frequent headline movers)
  APA: ["APA Corporation"],
  MRO: ["Marathon Oil"],
  SM: ["SM Energy"],
  CTRA: ["Coterra"],
  AR: ["Antero Resources"],
  EQT: ["EQT Corporation"],

  // Materials / Metals (macro-linked)
  AA: ["Alcoa"],
  TECK: ["Teck Resources"],
  SCCO: ["Southern Copper"],
  MP: ["MP Materials"],
  VALE: ["Vale"],

  // Healthcare / Biopharma (commonly referenced)
  HCA: ["HCA Healthcare"],
  UHS: ["Universal Health Services"],
  ICUI: ["ICU Medical"],
  SGENX: ["Seagen"],

  // Utilities / Infrastructure
  PCG: ["PG&E"],
  AES: ["AES Corporation"],
  NI: ["NiSource"],
  CNP: ["CenterPoint Energy"],

  // Popular ETFs not yet covered
  SCHG: ["Schwab U.S. Large-Cap Growth"],
  VOOG: ["Vanguard S&P 500 Growth"],
  VOOV: ["Vanguard S&P 500 Value"],
  IJR: ["iShares Core S&P Small-Cap"],
  MDY: ["SPDR S&P MidCap 400"],
  VIXY: ["ProShares VIX Short-Term Futures"],

  IBM: ["IBM"],
  DELL: ["Dell Technologies"],
  HPQ: ["HP"],
  HPE: ["Hewlett Packard Enterprise"],
  NOK: ["Nokia"],
  ERIC: ["Ericsson"],
  TTD: ["The Trade Desk"],
  RDDT: ["Reddit"],
  SPWR: ["SunPower"],
  BOX: ["Box"],

  // Consumer / Retail (highly visible)
  KMX: ["CarMax"],
  AZO: ["AutoZone"],
  ORLY: ["O'Reilly Automotive", "OReilly"],
  AAP: ["Advance Auto Parts"],
  GPC: ["Genuine Parts"],
  TSCO: ["Tractor Supply"],
  BGFV: ["Big 5 Sporting Goods"],
  HIBB: ["Hibbett"],
  CONN: ["Conn's"],

  // Travel / Leisure / Experiences
  EXPE: ["Expedia"],
  TRIP: ["TripAdvisor"],
  WYNN: ["Wynn Resorts"],
  LVS: ["Las Vegas Sands"],
  MGM: ["MGM Resorts"],
  CZR: ["Caesars Entertainment"],
  PENN: ["Penn Entertainment"],

  // Autos / Mobility
  GMED: ["Globus Medical"],
  MGA: ["Magna International"],
  APTV: ["Aptiv"],
  LEA: ["Lear"],
  VC: ["Visteon"],
  GOEV: ["Canoo"],
  FSR: ["Fisker"],
  PSNY: ["Polestar"],
  HOG: ["Harley-Davidson"],

  // Energy (widely discussed)
  SHEL: ["Shell"],
  SU: ["Suncor"],
  CNQ: ["Canadian Natural Resources"],
  IMO: ["Imperial Oil"],
  CVE: ["Cenovus"],
  ENB: ["Enbridge"],
  TRP: ["TC Energy"],
  PAA: ["Plains All American"],
  ET: ["Energy Transfer"],

  // Financials (common outside money-center banks)
  KKR: ["KKR"],
  BX: ["Blackstone"],
  APO: ["Apollo Global Management"],
  CG: ["Carlyle Group"],
  TROW: ["T. Rowe Price"],
  BEN: ["Franklin Resources"],
  AMP: ["Ameriprise"],
  LPLA: ["LPL Financial"],
  MKTX: ["MarketAxess"],
  NDAQ: ["Nasdaq Inc"],

  // Insurance (frequently referenced)
  RNR: ["RenaissanceRe"],
  MKL: ["Markel"],
  RE: ["Everest Re"],
  AIZ: ["Assurant"],
  THG: ["Hanover Insurance"],
  CNA: ["CNA Financial"],

  // Healthcare (very common)
  HIMS: ["Hims & Hers"],
  OSCR: ["Oscar Health"],
  GH: ["Guardant Health"],
  NTRA: ["Natera"],
  ILMN: ["Illumina"],
  PACB: ["Pacific Biosciences"],
  RXDX: ["Prometheus Biosciences"],
  SMMT: ["Summit Therapeutics"],

  // Industrials / Infrastructure
  GWW: ["Grainger"],
  URI: ["United Rentals"],
  TREX: ["Trex"],
  EXP: ["Eagle Materials"],
  SUM: ["Summit Materials"],
  AXON: ["Axon Enterprise"],
  GNRC: ["Generac"],
  FLOW: ["Flowserve"],
  BKR: ["Baker Hughes"],

  // Materials / Chemicals
  LYB: ["LyondellBasell"],
  HUN: ["Huntsman"],
  OLN: ["Olin"],
  AXTA: ["Axalta"],
  CC: ["Chemours"],
  NEU: ["NewMarket"],
  TROX: ["Tronox"],

  // Media / Content / Streaming
  WMG: ["Warner Music Group"],
  IAC: ["IAC"],

  // Consumer Brands (very common)
  KTB: ["Kontoor Brands"],
  CPRI: ["Capri Holdings"],
  HBI: ["Hanesbrands"],
  LEVI: ["Levi Strauss"],
  COLM: ["Columbia Sportswear"],
  WWW: ["Wolverine Worldwide"],
  NKEV: ["Nike"],

  // REITs (highly referenced)
  BXP: ["Boston Properties"],
  KIM: ["Kimco Realty"],
  FRT: ["Federal Realty"],
  REG: ["Regency Centers"],
  HST: ["Host Hotels"],
  REXR: ["Rexford Industrial"],
  COLD: ["Americold"],

  // Agriculture / Food (headline staples)
  ADM: ["Archer Daniels Midland"],
  BG: ["Bunge"],
  PPC: ["Pilgrim's Pride"],
  CALM: ["Cal-Maine Foods"],
};
