# Institutional Quant ML System Specification
# Version: 1.0.0
# Last Updated: 2025-11-12

system:
  name: "QuantTrade-ML"
  version: "1.0.0"
  objective: "Intraday long/short US equities"

objectives:
  primary_kpi: "after_cost_sharpe"
  targets:
    sharpe_ratio: 1.2
    max_drawdown_pct: 12
    profit_factor: 1.5
    annual_turnover: 20
  universe:
    tickers:
      [
        "NVDA",
        "AAPL",
        "GOOGL",
        "MSFT",
        "AMZN",
        "META",
        "TSLA",
        "AVGO",
        "LLY",
        "JPM",
        "WMT",
        "V",
        "ORCL",
        "MA",
        "XOM",
        "JNJ",
        "PLTR",
        "NFLX",
        "BAC",
        "ABBV",
        "COST",
        "AMD",
        "HD",
        "PG",
        "GE",
        "MU",
        "CSCO",
        "CVX",
        "UNH",
        "KO",
        "WFC",
        "MS",
        "IBM",
        "CAT",
        "CRM",
        "ADBE",
        "ACN",
        "PM",
        "QCOM",
        "LIN",
        "TXN",
        "VZ",
        "RTX",
        "AMGN",
        "DIS",
        "T",
        "INTC",
        "ISRG",
        "NEE",
        "LOW",
        "PFE",
        "HON",
        "AXP",
        "BKNG",
        "SPGI",
        "UNP",
        "SYK",
        "GS",
        "A",
        "AAL",
        "AAP",
        "ABNB",
        "ABT",
        "ACGL",
        "ADI",
        "ADM",
        "ADSK",
        "AEE",
        "AEP",
        "AES",
        "AFL",
        "AFRM",
        "AG",
        "AGNC",
        "AIG",
        "AIZ",
        "AJG",
        "AKAM",
        "ALB",
        "ALGN",
        "ALL",
        "ALLE",
        "AMAT",
        "AMCR",
        "AME",
        "AMR",
        "AMT",
        "ANET",
        "AON",
        "AOS",
        "APA",
        "APD",
        "APH",
        "APO",
        "ARE",
        "ARKG",
        "ATO",
        "AVY",
        "AWK",
        "AXON",
        "AZO",
        "BA",
        "BALL",
        "BAX",
        "BBWI",
        "BBY",
        "BDX",
        "BEN",
        "BF.B",
        "BIIB",
        "BIO",
        "BITF",
        "BK",
        "BKR",
        "BLK",
        "BMY",
        "BSX",
        "BTU",
        "BXP",
        "C",
        "CAG",
        "CAH",
        "CARR",
        "CB",
        "CBOE",
        "CBRE",
        "CCI",
        "CCL",
        "CDNS",
        "CDW",
        "CE",
        "CEG",
        "CF",
        "CFG",
        "CHD",
        "CHKP",
        "CHTR",
        "CI",
        "CINF",
        "CL",
        "CLX",
        "CMA",
        "CMCSA",
        "CME",
        "CMG",
        "CMI",
        "CMS",
        "CNC",
        "CNP",
        "COF",
        "COIN",
        "COP",
        "CPB",
        "CPRT",
        "CPT",
        "CRL",
        "CRWD",
        "CSGP",
        "CSX",
        "CTAS",
        "CTRA",
        "CTSH",
        "CTVA",
        "CVS",
        "D",
        "DAL",
        "DD",
        "DDOG",
        "DE",
        "DECK",
        "DG",
        "DGX",
        "DHI",
        "DHR",
        "DLR",
        "DLTR",
        "DOCU",
        "DOV",
        "DOW",
        "DPZ",
        "DRI",
        "DTE",
        "DUK",
        "DVA",
        "DVN",
        "DXCM",
        "EA",
        "EBAY",
        "ECL",
        "ED",
        "EFX",
        "EG",
        "EIX",
        "EL",
        "ELV",
        "EMN",
        "EMR",
        "ENPH",
        "EOG",
        "EPAM",
        "EQIX",
        "EQR",
        "EQT",
        "ES",
        "ESS",
        "ETN",
        "ETR",
        "EVRG",
        "EW",
        "EXAS",
        "EXC",
        "EXPD",
        "EXPE",
        "EXR",
        "F",
        "FANG",
        "FAST",
        "FCX",
        "FDS",
        "FE",
        "FICO",
        "FIS",
        "FITB",
        "FMC",
        "FOX",
        "FOXA",
        "FRT",
        "FTNT",
        "FTV",
        "GD",
        "GDDY",
        "GEHC",
        "GEN",
        "GILD",
        "GIS",
        "GL",
        "GLW",
        "GM",
        "GMAB",
        "GNRC",
        "GPC",
        "GPN",
        "GRMN",
        "GS",
        "GWRE",
        "HAL",
        "HAS",
        "HBAN",
        "HCA",
        "HIG",
        "HII",
        "HLT",
        "HOLX",
        "HOOD",
        "HPQ",
        "HRL",
        "HSIC",
        "HST",
        "HSY",
        "HUBB",
        "HUM",
        "HWM",
        "IEX",
        "IFF",
        "ILMN",
        "INCY",
        "INVH",
        "IP",
        "IQV",
        "IREN",
        "IRM",
        "IT",
        "ITW",
        "IVZ",
        "J",
        "JBHT",
        "JBLU",
        "JCI",
        "JKHY",
        "KDP",
        "KEY",
        "KHC",
        "KIM",
        "KLAC",
        "KMB",
        "KMI",
        "KMX",
        "KR",
        "KSS",
        "L",
        "LDOS",
        "LEN",
        "LH",
        "LHX",
        "LKQ",
        "LMT",
        "LNC",
        "LNT",
        "LRCX",
        "LULU",
        "LUV",
        "LVS",
        "LW",
        "LYB",
        "LYV",
        "M",
        "MAA",
        "MAR",
        "MARA",
        "MAS",
        "MCK",
        "MCO",
        "MDB",
        "MCD",
        "MDT",
        "MET",
        "MGM",
        "MHK",
        "MKC",
        "MKTX",
        "MLM",
        "MMC",
        "MMM",
        "MNST",
        "MO",
        "MOH",
        "MOS",
        "MPC",
        "MPWR",
        "MRNA",
        "MSI",
        "MSTR",
        "MTB",
        "MTCH",
        "MTD",
        "NCLH",
        "NDAQ",
        "NDSN",
        "NEM",
        "NET",
        "NI",
        "NKE",
        "NOC",
        "NOW",
        "NRG",
        "NSC",
        "NTRS",
        "NUE",
        "NVAX",
        "NVCR",
        "NVR",
        "NWL",
        "NWS",
        "NWSA",
        "NXPI",
        "O",
        "ODFL",
        "OKE",
        "OKTA",
        "OMC",
        "ON",
        "ORLY",
        "OTIS",
        "OXY",
        "PANW",
        "PATH",
        "PAYC",
        "PAYX",
        "PCAR",
        "PCG",
        "PEG",
        "PEP",
        "PGR",
        "PH",
        "PHM",
        "PKG",
        "PLD",
        "PNC",
        "PNR",
        "PNW",
        "POOL",
        "PPG",
        "PPL",
        "PRU",
        "PSA",
        "PSX",
        "PTC",
        "PUBM",
        "PYPL",
        "QRVO",
        "RCL",
        "REG",
        "REGN",
        "RF",
        "RHI",
        "RJF",
        "RL",
        "RMD",
        "ROK",
        "ROL",
        "ROP",
        "ROST",
        "RSG",
        "RVTY",
        "SBAC",
        "SBUX",
        "SCHW",
        "SHW",
        "SHOP",
        "SJM",
        "SLB",
        "SNA",
        "SNOW",
        "SO",
        "SOFI",
        "SPG",
        "STAG",
        "STE",
        "STLD",
        "STT",
        "STX",
        "STZ",
        "SWK",
        "SWKS",
        "SYF",
        "SYY",
        "TAP",
        "TDG",
        "TDOC",
        "TDY",
        "TEAM",
        "TECH",
        "TEL",
        "TER",
        "TFC",
        "TFX",
        "TGT",
        "TJX",
        "TMO",
        "TROW",
        "TRV",
        "TRGP",
        "TSCO",
        "TSN",
        "TT",
        "TTD",
        "TTWO",
        "TXT",
        "TYL",
        "UAL",
        "UPS",
        "UDR",
        "UHS",
        "ULTA",
        "URI",
        "USB",
        "VCYT",
        "VFC",
        "VICI",
        "VLO",
        "VMC",
        "VNO",
        "VRSK",
        "VRSN",
        "VRTX",
        "VTR",
        "VTRS",
        "WAB",
        "WAT",
        "WM",
        "WBD",
        "WDC",
        "WEC",
        "WELL",
        "WHR",
        "WMB",
        "WRB",
        "WST",
        "WTW",
        "WY",
        "WYNN",
        "XEL",
        "XRAY",
        "XYL",
        "YUM",
        "ZBH",
        "ZBRA",
        "ZION",
        "ZM",
        "ZS",
        "ZTS",
        "IBIT",
        "BITX",
        "RIOT",
        "UPST",
        "DKNG",
        "LCID",
        "RIVN",
        "APP",
        "PINS",
        "SE",
        "CPNG",
        "GRAB",
        "TOST",
        "DUOL",
        "RDDT",
        "HIMS",
        "SOUN",
        "BBAI",
        "RKLB",
        "ASTS",
        "IONQ",
        "RGTI",
        "QBTS",
        "OKLO",
        "SMR",
        "VRT",
        "SMCI",
        "MNDY",
      ]

    selection_rules: ""
  capital:
    max_leverage: 1.0
    max_weight_per_name: 0.20
    initial_capital: 100000

data:
  sources:
    primary: "schwab_api"
    bars: ["1m", "5m", "15m"]
    optional: ["l1_spreads", "volume_imbalance"]
  calendar:
    trading_days: "NYSE"
    market_hours: "09:30-16:00 ET"
    timezone: "America/New_York"
  bar_types:
    time_bars: [1, 5, 15] # minutes
    event_bars:
      cusum_threshold: 0.0015 # 0.15% price move
      dollar_bar_threshold: 1000000 # $1M
      volume_bar_threshold: 100000 # 100K shares
  windows:
    train_months: 4 # Reduced from 6 to fit 6 months of data
    test_months: 1
    embargo_bars: 10
    min_samples: 800
  storage:
    raw: "data/raw/{symbol}/{date}.parquet"
    processed: "data/processed/{freq}/features_{symbol}_{month}.parquet"
    models: "outputs/models/v{version}/{ticker}_{hash}.pkl"

features:
  schema_version: "v2"
  groups:
    returns:
      - "log_ret_1"
      - "log_ret_3"
      - "log_ret_5"
      - "log_ret_15"
    volatility:
      - "atr_14"
      - "realized_vol_10"
      - "bb_width_20"
      - "vol_zscore"
    momentum:
      - "rsi_3"
      - "rsi_7"
      - "rsi_14"
      - "macd_fast"
      - "kama_slope"
    price_location:
      - "zscore_vs_vwap"
      - "bb_position"
      - "dist_from_vwap_pct"
    time_context:
      - "minute_sin"
      - "minute_cos"
      - "day_of_week_sin"
      - "day_of_week_cos"
      - "is_first_30min"
      - "is_last_30min"
    liquidity:
      - "hl_range_pct"
      - "volume_zscore"
      - "spread_proxy"
      - "dollar_volume_ma"
    regime:
      - "vol_regime" # GMM k=4 classification
      - "trend_regime"
      - "liquidity_regime"
  engineering_rules:
    no_lookahead: true
    handle_missing: "forward_fill"
    outlier_clip: 5.0 # standard deviations

labels:
  method: "triple_barrier"
  parameters:
    tp_atr_mult: 1.5
    sl_atr_mult: 1.0
    timeout_bars: 15
  classes: ["up", "down", "neutral"]
  binary_mode: false # 3-class
  meta_labeling:
    enabled: true
    features: ["base_confidence", "regime", "spread_proxy"]

models:
  base:
    lgbm:
      objective: "multiclass"
      num_class: 3
      num_leaves: 31
      learning_rate: 0.03
      max_depth: 6
      min_child_samples: 50
      lambda_l1: 0.1
      lambda_l2: 0.1
      feature_fraction: 0.8
      bagging_fraction: 0.8
      early_stopping_rounds: 50
    logistic:
      penalty: "l2"
      C: 1.0
      solver: "lbfgs"
      max_iter: 1000
    tcn:
      filters: 64
      kernel_size: 3
      dilations: [1, 2, 4, 8, 16]
      dropout: 0.2
      sequence_length: 128
  ensemble:
    method: "stacking"
    meta_model: "lgbm"
    calibration: "isotonic"
    cv_folds: 5

validation:
  scheme: "walk_forward"
  walk_config:
    train_months: 6
    test_months: 1
    step_months: 1
  purged_kfold:
    n_splits: 5
    embargo_bars: 10
  selection_metric: "sharpe_after_costs"
  secondary_metrics:
    - "max_drawdown"
    - "profit_factor"
    - "turnover"
    - "avg_trade_pnl"
  threshold_sweep: [0.55, 0.60, 0.65, 0.70, 0.75]

execution:
  entry:
    long_threshold: 0.64
    short_threshold: 0.64
    require_meta_approval: true
    no_trade_windows:
      - "09:30-09:45" # Market open volatility
      - "15:45-16:00" # Market close
  exit:
    methods: ["tp", "sl", "timeout", "eod"]
    eod_flat_time: "15:58"
    min_hold_bars: 3
    cooldown_bars: 2
  position_sizing:
    method: "volatility_scaled"
    target_risk_pct: 0.25 # 0.25% per trade
    max_position_pct: 10 # 10% of capital
    scale_by: "atr_14"
  daily_limits:
    max_loss_multiple: 1.5 # × daily σ
    max_trades_per_symbol: 10
    max_trades_total: 30

portfolio:
  construction:
    method: "risk_parity" # or "mean_variance"
    lookback_bars: 60
    turnover_penalty: 0.5
  constraints:
    max_gross_leverage: 1.0
    max_sector_exposure: 0.30
    max_single_name: 0.20
  rebalance_frequency: "bar" # Every bar

costs:
  transaction:
    commission_pct: 0.001 # 0.1%
    fixed_per_trade: 0
  slippage:
    base_bps: 2.0
    vol_multiplier: 0.3
    participation_multiplier: 0.1
    model: "half_spread_proxy"
  spread_model:
    method: "hl_range_pct"
    cap_bps: 10.0

monitoring:
  live_kpis:
    - "pnl_ytd"
    - "sharpe_rolling_30d"
    - "hit_rate"
    - "avg_slippage"
    - "turnover"
    - "current_exposure"
    - "max_drawdown"
  drift_detection:
    feature_psi_threshold: 0.25
    score_calibration_ks_threshold: 0.10
    data_freshness_minutes: 5
  alerts:
    - type: "max_drawdown"
      threshold_pct: 10
    - type: "daily_loss"
      threshold_pct: 2
    - type: "model_drift"
      threshold: 0.25

deployment:
  canary:
    enabled: true
    allocation_pct: 10
    duration_days: 7
  versioning:
    track:
      - "data_window"
      - "feature_schema_hash"
      - "model_hash"
      - "scaler_hash"
      - "config_path"
    log_path: "outputs/versions/{timestamp}.json"
  rollback:
    enabled: true
    criteria:
      - "sharpe_degradation_pct: 30"
      - "max_drawdown_breach_pct: 15"
